### ISSUE TITLE
make -Wall clean

### ISSUE THREAD

**Issue by fabiangreffrath** [fabiangreffrath/rott#13]

**Comment by malespiaut** [comment]
I would recommend going step-by-step, and also taking into account `-Wextra`, `-Wpedantic`, and `-Wshadow`.

**Comment by fabiangreffrath** [comment]
I have a PR ready that fixes all `-Wall` warnings in one. It also adds `-Werror to the CI build.

**Comment by malespiaut** [comment]
I'm currently fixing some missing -Wall errors in the `wall` branch. I'll do a pull request as well. I don't know yet if my commits fits what you are expecting for your project.

**Comment by fabiangreffrath** [comment]
> I'm currently fixing some missing -Wall errors in the `wall` branch. I'll do a pull request as well. I don't know yet if my commits fits what you are expecting for your project.

I'm thankful for any contribution, really! Is your patch meant to be applied after my -Wall fixes branch?
