### ISSUE TITLE
Darkwar intro sequence not displaying on SDL2

### ISSUE THREAD

**Issue by jengelh** [fabiangreffrath/rott#2]
Version:  99e8523e425c35cbfcac3b876ec9cc5dc63558da
System: openSUSE Tumbleweed 20230629, SDL 2.28.0,
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) Xe Graphics (TGL GT2) (0x9a49)
    Version: 23.1.3
    Accelerated: yes
    Video memory: 15582MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```

The [San Nicolas intro sequence](https://www.youtube.com/watch?v=ITbehdRJUiY&t=82s) fails to display in the SDL2 port; the screen just stays black (both fullscreen and windows mode) while the music plays. The last known good version is the SDL1 port (1.1.2+svn287).

**Comment by fabiangreffrath** [comment]
Ouch! Any idea where exactly in the code the bug hides?
