### ISSUE TITLE
Wipe out unused code

### ISSUE THREAD

**Issue by malespiaut** [fabiangreffrath/rott#27]
Another bold proposal.

The codebase have its fair share of `#ifdef DEBUG`, `#if 0`, and unused code, which only gets in the way of readability.
I, for one, would be happy to meticulously remove all of that crust, one file at a time… with permission, of course.

**Comment by fabiangreffrath** [comment]
Yes, please! That was on my TODO list anyway.

**Comment by fabiangreffrath** [comment]
`DEVELOPMENT` is another such macro. Or do you know what it is/was good for?

**Comment by malespiaut** [comment]
So far it seems that `DEVELOPMENT` prints a lot of information on the standard output. On that note, I have suspected, while working on ROTT debug code a few years prior, that they had a physical printer printing info when debugging the game. But that's only a supposition.

**Comment by fabiangreffrath** [comment]
Fixed by https://github.com/fabiangreffrath/rott/commit/69822130def385a0c4e1295986f73dfe22ed0f87 ?

**Comment by malespiaut** [comment]
It is, yes!

**Comment by fabiangreffrath** [comment]
Not bad:
```
$ git diff 20211123 --shortstat
 197 files changed, 1872 insertions(+), 44096 deletions(-)
```
